name = "finki-hub-timetables-api"
main = "src/index.ts"
compatibility_date = "2025-02-06"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = true

[[routes]]
pattern = "timetables-api.finki-hub.com/*"
zone_name = "finki-hub.com"
