name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    uses: finki-hub/.github/.github/workflows/cloudflare-pages.yaml@main
    with:
      build-command: npm run build
      output-directory: dist
